"""Local LLM integration utilities for disruption analysis."""

from __future__ import annotations

import json
import time

try:
    import requests
except ImportError:  # pragma: no cover - handled through fallback behavior
    requests = None


OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "llama3"
REQUIRED_FIELDS = ("disruption_score", "downtime", "risk_level", "reason")
VALID_RISK_LEVELS = {"LOW", "MEDIUM", "HIGH"}
FALLBACK_RESULT = {
    "disruption_score": 0.5,
    "downtime": 0.3,
    "risk_level": "MEDIUM",
    "reason": "Fallback due to parsing failure",
}


def build_prompt(data: dict) -> str:
    """Build a strict prompt that instructs the model to return JSON only.

    Args:
        data: Structured zone-level input data for disruption analysis.

    Returns:
        A prompt string formatted for the Ollama generate endpoint.
    """
    return f"""
You are an AI risk engine for gig delivery workers.

Analyze the following city zone conditions and estimate disruption impact.

The 'events' field contains real news headlines. You must infer whether these indicate disruptions such as protests, rallies, strikes, festivals, or normal conditions.

Rules:
- High temperature increases disruption moderately.
- Traffic affects delivery speed and worker mobility.
- The events field contains real-world headlines, not labels, so infer likely operational impact from the news text.
- Rainfall impact rules:
  - rain > 80 means VERY HIGH disruption
  - rain between 50 and 80 means HIGH disruption
  - rain between 20 and 50 means MODERATE disruption
  - rain < 20 means LOW disruption
- If rainfall is above 80, disruption_score MUST be at least 0.7 regardless of other factors.
- Do not output disruption_score = 0 if rain > 20 or traffic is not low.
- Traffic impact rules:
  - high traffic means strong disruption
  - medium traffic means moderate disruption
  - low traffic means minor disruption
- Event impact rules:
  - strike or rally means HIGH disruption
  - festival is mixed and can increase or decrease downtime depending on context
  - normal news with no clear disruption signal means low impact
- disruption_score must be a float between 0 and 1.
- downtime must be a float between 0 and 1.
- risk_level must be exactly one of: LOW, MEDIUM, HIGH.
- reason must be a short plain-English explanation based on the signals.

Input data:
- rain: {data.get("rain")}
- temp: {data.get("temp")}
- traffic: {data.get("traffic")}
- events: {data.get("events")}

ONLY return valid JSON.
Do not include markdown.
Do not include backticks.
Do not include any explanation outside the JSON object.

Required JSON schema:
{{
  "disruption_score": 0.0,
  "downtime": 0.0,
  "risk_level": "LOW",
  "reason": "short explanation"
}}
""".strip()


def call_llm(prompt: str) -> str | None:
    """Send a prompt to the local Ollama server and return the raw response.

    Args:
        prompt: Prompt text to send to the local model.

    Returns:
        The raw text generated by the model, or None if the request fails.
    """
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
    }

    if requests is None:
        print("ERROR: requests library not installed. LLM call skipped.")
        return None

    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=30)
        response.raise_for_status()
        response_data = response.json()
        return response_data.get("response")
    except (requests.RequestException, ValueError):
        return None


def _extract_json_object(response: str) -> str | None:
    """Extract the first balanced JSON object from a raw model response."""
    start_index = response.find("{")
    if start_index == -1:
        return None

    depth = 0
    in_string = False
    escape_next = False

    for index in range(start_index, len(response)):
        character = response[index]

        if escape_next:
            escape_next = False
            continue

        if character == "\\" and in_string:
            escape_next = True
            continue

        if character == '"':
            in_string = not in_string
            continue

        if in_string:
            continue

        if character == "{":
            depth += 1
        elif character == "}":
            depth -= 1
            if depth == 0:
                return response[start_index : index + 1]

    return None


def _validate_output(data: dict) -> dict | None:
    """Validate and normalize parsed LLM output."""
    for field in REQUIRED_FIELDS:
        if field not in data:
            return None

    try:
        disruption_score = float(data["disruption_score"])
        downtime = float(data["downtime"])
    except (TypeError, ValueError):
        return None

    risk_level = str(data["risk_level"]).upper()
    reason = str(data["reason"]).strip()

    if not 0 <= disruption_score <= 1:
        return None

    if not 0 <= downtime <= 1:
        return None

    if risk_level not in VALID_RISK_LEVELS:
        return None

    if not reason:
        return None

    return {
        "disruption_score": disruption_score,
        "downtime": downtime,
        "risk_level": risk_level,
        "reason": reason,
    }


def parse_llm_output(response: str | None) -> dict | None:
    """Parse and validate structured JSON from a raw model response.

    Args:
        response: Raw model output text.

    Returns:
        A validated result dictionary, or None if parsing fails.
    """
    if not response:
        return None

    json_text = _extract_json_object(response)
    if not json_text:
        return None

    try:
        parsed_data = json.loads(json_text)
    except json.JSONDecodeError:
        return None

    if not isinstance(parsed_data, dict):
        return None

    return _validate_output(parsed_data)


def get_llm_result(data: dict) -> dict:
    """Run the full LLM analysis flow with retry and fallback behavior.

    Args:
        data: Structured zone-level input data.

    Returns:
        A validated disruption analysis result.
    """
    prompt = build_prompt(data)

    for attempt in range(3):
        raw_response = call_llm(prompt)
        parsed_result = parse_llm_output(raw_response)
        if parsed_result is not None:
            return parsed_result

        if attempt < 2:
            time.sleep(0.5)

    return FALLBACK_RESULT.copy()
