"""Tamil Nadu city boundary configuration for zone generation."""

from __future__ import annotations


CITIES = {
    "chennai": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 1",
        "code": "TN_CHN",
        "lat_min": 12.90,
        "lat_max": 13.20,
        "lng_min": 80.10,
        "lng_max": 80.35,
    },
    "coimbatore": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_CBE",
        "lat_min": 10.95,
        "lat_max": 11.10,
        "lng_min": 76.90,
        "lng_max": 77.10,
    },
    "madurai": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_MDU",
        "lat_min": 9.85,
        "lat_max": 10.05,
        "lng_min": 78.00,
        "lng_max": 78.20,
    },
    "tiruchirappalli": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_TRY",
        "lat_min": 10.75,
        "lat_max": 10.90,
        "lng_min": 78.60,
        "lng_max": 78.80,
    },
    "salem": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_SLM",
        "lat_min": 11.60,
        "lat_max": 11.75,
        "lng_min": 78.00,
        "lng_max": 78.20,
    },
    "erode": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_ERD",
        "lat_min": 11.30,
        "lat_max": 11.45,
        "lng_min": 77.65,
        "lng_max": 77.80,
    },
    "tirunelveli": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_TNV",
        "lat_min": 8.65,
        "lat_max": 8.80,
        "lng_min": 77.65,
        "lng_max": 77.80,
    },
    "vellore": {
        "state": "Tamil Nadu",
        "state_code": "TN",
        "tier": "Tier 2",
        "code": "TN_VLR",
        "lat_min": 12.85,
        "lat_max": 12.98,
        "lng_min": 79.10,
        "lng_max": 79.25,
    },
}
